### ISSUE TITLE
EMG setup add Sampling Rate explanatory text

### ISSUE THREAD

**Issue by cewall** [NESCent/feedingdb#26]
Sampling Rate needs explanatory text [here](https://feedexp.org/admin/feed/emgsetup/63/)

Add text: Recording rate, entered below, is a required field for each sensor channel. Please indicate here if data are sampled at a different rate from the recording rate for individual channels.

**Comment by hlapp** [comment]
I am going to assume this direction applies to all sensor, not just EMG. If it is specific to EMG, I'll need to verify with SquishyMedia how to address this.

**Comment by cewall** [comment]
It was meant to apply only to EMG, but it certainly does apply to any trial where data might be sampled at a different rate than they were recorded.

**Comment by cewall** [comment]
So the answer is Yes it does apply to Sampling Rate for all sensors
