### ISSUE TITLE
NOTES about all sensors .... critical addition of explanatory text

### ISSUE THREAD

**Issue by cewall** [NESCent/feedingdb#35]
[here](https://feedexp.org/admin/feed/emgsetup/518/edit/)

add explanatory text before the colon: (please provide detailed information on bandpass filtering is used)

**Comment by hlapp** [comment]
@cewall I can't identify where you need this to appear. Can you pinpoint the field by its label? (And I'm not sure what you mean by _before the colon_. Perhaps what you mean is to add a help text for the field labeled "_Notes About All Sensors And Channels In This Setup_"?)

**Comment by cewall** [comment]
It should go after this text: Notes about all sensors and channels in this setup: 

so that it reads
Notes about all sensors and channels in this setup (please provide detailed information on bandpass filtering if used):

**Comment by hlapp** [comment]
Note that this will change the label for this field in this way anywhere in the application. That's probably not what you want. Why can this not be the help text for the field (in which case it goes beneath, or is hidden as the "(i)" tooltip)?

**Comment by cewall** [comment]
You are right.  We only want it to appear on EMG.  This should definitely be the help text for the field, then.
