### ISSUE TITLE
CHANGE TITLES EXPERIMENT SESSION TRIAL upload pages

### ISSUE THREAD

**Issue by cewall** [NESCent/feedingdb#36]
Make changes to "Title" with following text and places:
Change to: Experiment Title [here](https://feedexp.org/admin/feed/experiment/add/?study=90)
Change to: Session Title [here](url  https://feedexp.org/admin/feed/session/add/?experiment=205)
Change to: Trial Title [here](url  https://feedexp.org/admin/feed/trial/add/?session=219)

**Comment by hlapp** [comment]
@cewall you did not link the target pages for the other two label changes. Note that these label changes are universal throughout the site, not just on one single page. Are these labels that you'd like changed all on the same page, or on different pages? If they are on distinct pages already, then the page will give the context (i.e., whether the page is about an experiment, a session, a trial, etc), and including it again in the label is redundant.

**Comment by cewall** [comment]
Examples of where the title for Session and Trial appear are as follows:
Session Title: [here](https://feedexp.org/admin/feed/session/146/edit/?experiment=38)
Trial title: [here](https://feedexp.org/admin/feed/trial/171/edit/?study=13)

They are on distinct pages already, and I agree that the page gives the context, but Chris Vinyard and Susan Williams requested this change because they thought that only having the text "Title" was confusing for Experiment, Session and Trial.

If this is a pain to do (and/or requires changing multiple places that might be hard to find in the code), we can not do it and leave it for FEED3.

**Comment by hlapp** [comment]
I suggest to wait and see whether this is confirmed as a real issue during upload of additional data.

**Comment by cewall** [comment]
I agree

**Comment by hlapp** [comment]
@cewall: I figured out how to change the label and it was a small enough change that I went ahead and changed it.
