### ISSUE TITLE
Contact address in README needs to be updated

### ISSUE THREAD

**Issue by hlapp** [NESCent/feedingdb#38]
The [README] in the Github repository lists NESCent street address and phone numbers:
```
National Evolutionary Synthesis Center
2024 W. Main Street, Suite A200
Durham, NC 27705-4667
Tel: (919) 668-4551
Fax: (919) 668-9198
```
This should arguably be changed. Delete and leave only email contact address, or substitute with another address (@cewall's, for example)?

[README]: https://github.com/NESCent/feedingdb/blob/17bdc302af92e39c49bba24cc84e02351f31521f/README.md

**Comment by cewall** [comment]
I think it is best to substitute with only an email contact address (cw19@duke.edu would be fine I guess??)  
What is the README in the github repository?  Is it a place that a db developer would go to in order to figure out how the code works?

**Comment by hlapp** [comment]
@cewall: yes, this is what one would first look at (and what Github first presents) when visiting the source code repository.
